// Local: Services/LocalCharacterService.cs

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JujutsuDle.Models;

public class LocalCharacterService : ICharacterService
{
    private readonly List<Character> _allCharacters;

    public LocalCharacterService()
    {
        _allCharacters = new List<Character>
    {
        // --- Alunos de Tóquio ---
        new Character { Id = 1, Name = "Yuji Itadori", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.CorpoACorpo, DebutYear = 2018, PhotoUrl = "https://files.shapes.inc/api/files/avatar_b1684a84-7ccb-4333-bfee-0d8d75b3711d.png" },
        new Character { Id = 2, Name = "Megumi Fushiguro", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio", "Clã Zen'in"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.Shikigami, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/_G-K2SjwQvzCU1iQeZTv_5cX8TPxG6uPPN0-LWQu2X4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJzLmNvbS9p/bWFnZXMvaGQvbWVn/dW1pLWZ1c2hpZ3Vy/by1pbnRlbnNlLWdh/emUtdW1iZG90ZnFu/dXJ0dDA3ei5qcGc" },
        new Character { Id = 3, Name = "Nobara Kugisaki", Gender = Gender.Feminino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/Cjd2ZNJk10P22JqKS6_3P8dWI64pIV62p9-RFdgp3BY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9ibG9n/Z2VyLmdvb2dsZXVz/ZXJjb250ZW50LmNv/bS9pbWcvYi9SMjl2/WjJ4bC9BVnZYc0Vn/Z3dLYzVNdURkSFVH/ZE1yN0NXUVhZR1I5/TktBUG03dDlfZGg2/V3F4cHZKdE1sOW9v/N3pUa3V2OWRpcGFl/ekJ5Mm5TdzJMZ2dN/elpYaVlDVkNQSGpy/bzlVeUNaZVlqT3Zr/OF8tRXBlV1dJeU9p/Uk9JU3o3a1RkRXVn/NDMwRXJMVXhVa1Zv/dEQzbE5jZjlvVkhO/MW80a1JrTDZrTlZN/UkdUQ2Y1cVdoQ2lj/TnlLbHNoM2lQWGV6/OHRPSU9COXhmL3Mx/NjAwMC1ydy9ub2Jh/cmEtcGZwLTMucG5n" },
        new Character { Id = 4, Name = "Maki Zen'in", Gender = Gender.Feminino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio", "Clã Zen'in"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.ArmaAmaldiçoada, DebutYear = 2017, PhotoUrl = "https://imgs.search.brave.com/Gn1oY5sW2xvr3TDWe1G6w5Qrb1YNGZHjnzudC22FFGw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9ibG9n/Z2VyLmdvb2dsZXVz/ZXJjb250ZW50LmNv/bS9pbWcvYi9SMjl2/WjJ4bC9BVnZYc0Vp/b0VoT1V6aW10a3lq/TFhaWmRCVHhXWmpp/d2lNd21YbTc5c3Bz/cXgtM20tSWkxUmZ3/bkdDX2xtc2wyelRD/ZGFIUnpUdzVpb2oy/NWVvVGRkWFFuYTdP/YmFXY2J4bU1kZE1v/T0hVWmpNcHBwTjhZ/T2hoWkxEdW1ROTJR/M0FPSUc2T0xiUDNu/aEt1Q0dqQXRocWF2/VjAyZldiRUpQSUZQ/STllaS1SOXJHV3hP/SHBFclFVLU82YjhQ/NFh3eExsZHhuL3Mx/NjAwMC1ydy9tYWtp/LXBmcC0yMy5qcGc" },
        new Character { Id = 5, Name = "Toge Inumaki", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2017, PhotoUrl = "https://imgs.search.brave.com/Wf_XQHMni5EZVlla_klriwl-UoYHHgoazL5NWdoZOUc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzE0LzFi/LzZkLzE0MWI2ZDgw/NjRmY2JmZWI4YWI1/ZDAwODYxMzQ0ZmI4/LmpwZw" },
        new Character { Id = 6, Name = "Panda", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.CorpoAmaldiçoado, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.CorpoACorpo, DebutYear = 2017, PhotoUrl = "https://imgs.search.brave.com/vR1mguPsKB_4LhggxB_ozR2Wpzw9fyiqmYd633pNDQg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMwLmdhbWVyYW50/aW1hZ2VzLmNvbS93/b3JkcHJlc3Mvd3At/Y29udGVudC91cGxv/YWRzLzIwMjQvMDEv/cGFuZGEtd2l0aC1h/cm1iYW5kLWluLWp1/anV0c3Uta2Fpc2Vu/LmpwZz9xPTQ5JmZp/dD1jcm9wJnc9ODI1/JmRwcj0y" },
        new Character { Id = 7, Name = "Yuta Okkotsu", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2017, PhotoUrl = "https://imgs.search.brave.com/PCNPoDX3tlqrGaJDHBW1dqMPhTChgrMru01sF3bei4I/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hdmF0/YXJmaWxlcy5hbHBo/YWNvZGVycy5jb20v/MzY5L3RodW1iLTM1/MC0zNjk3MTgud2Vi/cA" },
        new Character { Id = 8, Name = "Kinji Hakari", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2021, PhotoUrl = "https://imgs.search.brave.com/89mBVgrj9Jtqx45-BO2b-6LerkwevQ2bb-EtVbA56y8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2FjLzE2/L2ZlL2FjMTZmZTgx/N2EwYzAwMzYwZWRm/NTk3MTZjZDRiOWRi/LmpwZw" },
        new Character { Id = 9, Name = "Kirara Hoshi", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2021, PhotoUrl = "https://imgs.search.brave.com/v891MrNI6MruXhfnTmKVNEWTQBMg-PNQRSVbmI3w3i4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2E5L2M1/LzgyL2E5YzU4Mjcx/NmQ3OTlkNGUyYmZm/ZWMzOTE2YTIyZDU5/LmpwZw" },

        // --- Alunos de Quioto ---
        new Character { Id = 10, Name = "Aoi Todo", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Quioto"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/de0WQWjV6BDTX34QcEttEjCH7nmfmJcXoskcjx7woXQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzhlLzZl/L2Y0LzhlNmVmNDM2/OTUwMjdlMmEwYTZj/M2Q5ODk2NDBhMjRl/LmpwZw" },
        new Character { Id = 11, Name = "Mai Zenin", Gender = Gender.Feminino, Affiliations = new List<string>{"Escola Jujutsu de Quioto", "Clã Zen'in"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.ArmaAmaldiçoada, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/cwAYn1Omv7cIYISpOU9L2lfQdmMiGKCYHI_LeOsbWUs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzFiL2I2/LzljLzFiYjY5YzQw/YmQ2YmZlNjQ2ZmRl/ODBhYWFlNzBmZDc5/LmpwZw" },
        new Character { Id = 12, Name = "Noritoshi Kamo", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Quioto", "Clã Kamo"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/dOAQo6h8QgVrpa0I6iJGlYiZdP3edtslFLFJh8jRrro/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzRjL2Ey/L2UzLzRjYTJlMzMx/YTc0ODJiOGNhMDI4/ZjQ0MjNiMzdiZTEx/LmpwZw" },
        new Character { Id = 13, Name = "Kasumi Miwa", Gender = Gender.Feminino, Affiliations = new List<string>{"Escola Jujutsu de Quioto"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.ArmaAmaldiçoada, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/gquHvUeZcU12p0aXKsrCtsPYGAdCyGUhq8gWQC0r-sQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzdkL2Fh/LzRjLzdkYWE0Yzc2/NGEzODdlNTk4ZDE3/MWU1ZDUwOGM3NjZj/LmpwZw" },
        new Character { Id = 14, Name = "Momo Nishimiya", Gender = Gender.Feminino, Affiliations = new List<string>{"Escola Jujutsu de Quioto"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/I4EVKGKSQtOV-e54hX5NlvFdDKWk3dYED7dJuenVJYw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzAzLzBi/LzA0LzAzMGIwNDY5/ZjRlNTI3YWMzMGMx/OGI2OGMwMWViODhi/LmpwZw" },
        new Character { Id = 15, Name = "Mechamaru", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Quioto"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/uG1ExUbTCnNjJPjvuqnolrOQJ7oAxfhB610q7l6KwkU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90aGlj/Yy11d3UubXl3YWlm/dWxpc3QubW9lL3dh/aWZ1cy9rb2tpY2hp/LW11dGEvNHlySFVk/MjZkdmFaMDhiSFhr/Wm1Ra2NXTTRmeUtR/Nk9jcmpNYWpwRi5q/cGc_Y2xhc3M9dGh1/bWJuYWls" },
        
        // --- Feiticeiros Profissionais ---
        new Character { Id = 16, Name = "Satoru Gojo", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2017, PhotoUrl = "https://imgs.search.brave.com/wDM--4jWo0hFSHLHlT5zNeiCIdCQ4VP2122llJ1Z6mc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzhjLzli/LzA3LzhjOWIwN2U1/ZjI1Yjc3NzYxOTBi/ZjlkZTRkYTYwYzQ3/LmpwZw" },
        new Character { Id = 17, Name = "Kento Nanami", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.ArmaAmaldiçoada, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/lUekKunxEl54clTrR9M6EpLYUAMo0SfZ2pBWwXlpuio/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJhY2Nlc3Mu/Y29tL2Z1bGwvNTY2/MTUzMS5wbmc" },
        new Character { Id = 18, Name = "Mei Mei", Gender = Gender.Feminino, Affiliations = new List<string>{"Nenhuma"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.ArmaAmaldiçoada, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/S4XN1h6cpFOean9-Dd6JhetV5Woq351OLwV-j4Zzt-I/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzc4L2U2/LzRhLzc4ZTY0YTVj/MzM0NjdkMjFmZmE2/Yjc5NjIyMmE1ZTVi/LmpwZw" },
        new Character { Id = 19, Name = "Utahime Iori", Gender = Gender.Feminino, Affiliations = new List<string>{"Escola Jujutsu de Quioto", "Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/CbOayPbDuz_YqnDkVJjBR-rYmEThcG9MoPpkpRx1PKQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2NmLzJi/Lzg3L2NmMmI4Nzhm/ZWVkM2VjZWMwOTA1/MTQ3N2FhODVmZGVl/LmpwZw" },
        new Character { Id = 20, Name = "Takuma Ino", Gender = Gender.Masculino, Affiliations = new List<string>{"Grupo do Nanami"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2020, PhotoUrl = "https://imgs.search.brave.com/ZCkSPHYX4xHBe_TP1zmKwhv2F00uUdizSmaZN5xOZ2A/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzMyLzE0/LzNiLzMyMTQzYjk4/ZGMxOTVjMWY1MjFj/ZjhiNjEzZGZiMWZh/LmpwZw" },
        new Character { Id = 21, Name = "Shoko Ieiri", Gender = Gender.Feminino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/DLiHoR1a-djAIPVTMeHnUrEnKKmMHZFIG2FvnQje7qw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMtd2l4bXAtZWQz/MGE4NmI4YzRjYTg4/Nzc3MzU5NGMyLndp/eG1wLmNvbS9mLzEx/NGIyM2NmLWJjMzYt/NDNmOS04MmU2LWQw/OWNlYmRkM2FhNi9k/Z3VrbG1lLTllODEx/MGIwLTg3NzYtNGY3/MC04ODBlLTdmNzBi/YjNkYWNjOS5qcGc_/dG9rZW49ZXlKMGVY/QWlPaUpLVjFRaUxD/SmhiR2NpT2lKSVV6/STFOaUo5LmV5Snpk/V0lpT2lKMWNtNDZZ/WEJ3T2pkbE1HUXhP/RGc1T0RJeU5qUXpO/ek5oTldZd1pEUXhO/V1ZoTUdReU5tVXdJ/aXdpYVhOeklqb2lk/WEp1T21Gd2NEbzNa/VEJrTVRnNE9UZ3lN/alkwTXpjellUVm1N/R1EwTVRWbFlUQmtN/alpsTUNJc0ltOWlh/aUk2VzF0N0luQmhk/R2dpT2lKY0wyWmNM/ekV4TkdJeU0yTm1M/V0pqTXpZdE5ETm1P/UzA0TW1VMkxXUXdP/V05sWW1Sa00yRmhO/bHd2WkdkMWEyeHRa/UzA1WlRneE1UQmlN/QzA0TnpjMkxUUm1O/ekF0T0Rnd1pTMDNa/amN3WW1JelpHRmpZ/emt1YW5CbkluMWRY/U3dpWVhWa0lqcGJJ/blZ5YmpwelpYSjJh/V05sT21acGJHVXVa/RzkzYm14dllXUWlY/WDAucXR2Q1FjZlEy/cVFkNzcwbTdyOW56/R2QzU3oxbG50NEww/NEFkQTIwSkI3dw" },
        new Character { Id = 22, Name = "Masamichi Yaga", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.CorpoACorpo, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/6oAA8bT_bbhg88SQib0xsSWRaWKh-sOOQ_FKkws49Wk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/YW5pc2VhcmNoLmRl/L2ltYWdlcy9jaGFy/YWN0ZXIvY292ZXIv/OTcvOTc2MTdfNDAw/LndlYnA" },
        new Character { Id = 23, Name = "Yoshinobu Gakuganji", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Quioto"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/dqq3Y08I2_1s_RXhf9suP3-AYsAn6rqIYZpD1PqWztg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzViLzk0/L2UzLzViOTRlMzM0/YjgyNDc5ZjRmN2Rj/NzliMWJmYjEwMWZj/LmpwZw" },
        new Character { Id = 24, Name = "Yuki Tsukumo", Gender = Gender.Feminino, Affiliations = new List<string>{"Nenhuma"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.Shikigami, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/mm35F4OsjTO2vXI7BLZPyccYTV_dWFTh3L1yW6YBj-s/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/cGZwcy5nZy9wZnBz/LzcyODgteXVraS10/c3VrdW1vLnBuZw" },
        new Character { Id = 25, Name = "Atsuya Kusakabe", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.ArmaAmaldiçoada, DebutYear = 2020, PhotoUrl = "https://imgs.search.brave.com/Jlqs2tIBY9rifmYOkTLooFngzCBDGRkPM4vcc4DIKqo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/YW5pc2VhcmNoLmZy/L2ltYWdlcy9jaGFy/YWN0ZXIvY292ZXIv/OTcvOTc2NDZfNDAw/LndlYnA" },

        // --- Antagonistas, Maldições e Outros ---
        new Character { Id = 26, Name = "Sukuna", Gender = Gender.Masculino, Affiliations = new List<string>{"Nenhuma"}, Species = Species.Maldição, Classification = Classification.MestreDeMaldição, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/ne-2V0FNqw8TpgxnU07CfhIHH4QP508-20nRyBo7XTc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9wcmV2/aWV3LnJlZGQuaXQv/aGVpYW4tZXJhLXN1/a3VuYS1pLWxvdmUt/aG93LXVnbHktYW5k/LXNxdWFyZS1oZS1p/cy1hbG9uZy12MC1o/N2Z3emkwaGZ2bWMx/LnBuZz93aWR0aD02/NDAmY3JvcD1zbWFy/dCZhdXRvPXdlYnAm/cz0zYjlhM2Q1OTVi/Y2Y5YWE1NDFlMDg0/ZDIyZmNmZjZiMDdi/M2UxMTdm" },
        new Character { Id = 27, Name = "Mahito", Gender = Gender.Masculino, Affiliations = new List<string>{"Grupo do Kenjaku"}, Species = Species.Maldição, Classification = Classification.MestreDeMaldição, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/Kim7weJCRth_dmDIK-qpwOwJBwFkKWjm5GTPF2oVszY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2IxL2Zl/L2E1L2IxZmVhNWU2/MjIyMTNkY2RiYTVk/NTllOTY3NGYzNzVj/LmpwZw" },
        new Character { Id = 28, Name = "Jogo", Gender = Gender.Masculino, Affiliations = new List<string>{"Grupo do Kenjaku"}, Species = Species.Maldição, Classification = Classification.MestreDeMaldição, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/dSHlEtQbFJOF0eH27xhQjIkbvFIZi628KES2-qY5tUQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXM0LmFscGhhY29k/ZXJzLmNvbS8xMjMv/dGh1bWItNDQwLTEy/MzM0NjUud2VicA" },
        new Character { Id = 29, Name = "Hanami", Gender = Gender.Masculino, Affiliations = new List<string>{"Grupo do Kenjaku"}, Species = Species.Maldição, Classification = Classification.MestreDeMaldição, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/0b6dtB2h-Khvu_83eb2NRRoFXcuijshQiA7Pu1t0TD4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pMC53/cC5jb20vY29kaWdv/ZXNwYWd1ZXRpLmNv/bS93cC1jb250ZW50/L3VwbG9hZHMvMjAy/My8wOS9oYW5hbWkt/cXVpZW4tZXMtanVq/dXRzdS1rYWlzZW4u/anBnP2ZpdD03Njgs/NDMyJnNzbD0x" },
        new Character { Id = 30, Name = "Dagon", Gender = Gender.Masculino, Affiliations = new List<string>{"Grupo do Kenjaku"}, Species = Species.Maldição, Classification = Classification.MestreDeMaldição, CombatStyle = CombatStyle.Shikigami, DebutYear = 2020, PhotoUrl = "https://imgs.search.brave.com/2cw8cWWDj4NOAzvHb2O9VAQp2speGjCOFENw8_3VuQg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMtd2l4bXAtZWQz/MGE4NmI4YzRjYTg4/Nzc3MzU5NGMyLndp/eG1wLmNvbS9mL2U3/N2Y2ZTdlLWQ2ZDUt/NDVkYS05NmZjLTNj/Mjc3NmMxYmE4Zi9k/aDR0cGdoLTViZDk2/YWE0LTUzNjQtNDFm/OC1hOTBlLTVhYzZl/MTUzMTk1ZC5qcGcv/djEvZmlsbC93XzEy/ODAsaF8xMjY0LHFf/NzUsc3RycC9kYWdv/bl9ieV9jbGFya3J1/bGVzX2RoNHRwZ2gt/ZnVsbHZpZXcuanBn/P3Rva2VuPWV5SjBl/WEFpT2lKS1YxUWlM/Q0poYkdjaU9pSklV/ekkxTmlKOS5leUp6/ZFdJaU9pSjFjbTQ2/WVhCd09qZGxNR1F4/T0RnNU9ESXlOalF6/TnpOaE5XWXdaRFF4/TldWaE1HUXlObVV3/SWl3aWFYTnpJam9p/ZFhKdU9tRndjRG8z/WlRCa01UZzRPVGd5/TWpZME16Y3pZVFZt/TUdRME1UVmxZVEJr/TWpabE1DSXNJbTlp/YWlJNlcxdDdJbWhs/YVdkb2RDSTZJanc5/TVRJMk5DSXNJbkJo/ZEdnaU9pSmNMMlpj/TDJVM04yWTJaVGRs/TFdRMlpEVXRORFZr/WVMwNU5tWmpMVE5q/TWpjM05tTXhZbUU0/Wmx3dlpHZzBkSEJu/YUMwMVltUTVObUZo/TkMwMU16WTBMVFF4/WmpndFlUa3daUzAx/WVdNMlpURTFNekU1/TldRdWFuQm5JaXdp/ZDJsa2RHZ2lPaUk4/UFRFeU9EQWlmVjFk/TENKaGRXUWlPbHNp/ZFhKdU9uTmxjblpw/WTJVNmFXMWhaMlV1/YjNCbGNtRjBhVzl1/Y3lKZGZRLkJDS281/cTVQVG9SdkR6MGhV/eEdTSVRMOGlmOWp4/VUpkSTBmNTJjdXZm/TkU" },
        new Character { Id = 31, Name = "Choso", Gender = Gender.Masculino, Affiliations = new List<string>{"Irmãos Amaldiçoados"}, Species = Species.Híbrido, Classification = Classification.MestreDeMaldição, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2019, PhotoUrl = "https://imgs.search.brave.com/47WlzVyg9D2uvWrhRvRH_9Xm4kNTS3fbJ_AgyTQyksY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzA0Lzhh/L2M3LzA0OGFjN2Mz/MGMwMzI2YzA0ZDI0/MGRiNTQ0OTA4ZGVm/LmpwZw" },
        new Character { Id = 32, Name = "Eso", Gender = Gender.Masculino, Affiliations = new List<string>{"Irmãos Amaldiçoados"}, Species = Species.Híbrido, Classification = Classification.MestreDeMaldição, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2019, PhotoUrl = "https://imgs.search.brave.com/Tdr0cB4pVRUjuyXwQ6k4w4X_NkOOdbiZ8EhKE6y-6r4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzA4L2Zk/LzllLzA4ZmQ5ZTdi/Njg5MjM5NjRiZmM2/MWJiZWUyZmM2ODBh/LmpwZw" },
        new Character { Id = 33, Name = "Kechizu", Gender = Gender.Masculino, Affiliations = new List<string>{"Irmãos Amaldiçoados"}, Species = Species.Híbrido, Classification = Classification.MestreDeMaldição, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2019, PhotoUrl = "https://imgs.search.brave.com/7AP6XxjLnzp9X3rStSkYKVDILuDtVyLdL7st1r3BXa4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMud2lraWEubm9j/b29raWUubmV0L2p1/anV0c3Uta2Fpc2Vu/L2ltYWdlcy8zLzM4/L0tlY2hpenVfLV9B/bmltZS5qcGcvcmV2/aXNpb24vbGF0ZXN0/L3NjYWxlLXRvLXdp/ZHRoLWRvd24vMjY4/P2NiPTIwMjEwMzIw/MTMzNTQ1JnBhdGgt/cHJlZml4PWVz" },
        new Character { Id = 34, Name = "Suguru Geto", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio", "Grupo do Geto"}, Species = Species.Humano, Classification = Classification.UsuárioDeMaldição, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2017, PhotoUrl = "https://imgs.search.brave.com/I4b3vi44F0OrFcSYs2Bd-eTu5YX-kTZsIc8sf-XZ9cA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzcxLzg0/L2RkLzcxODRkZGFk/ZjRiMjk4NzA5M2M0/MzEzNDY3NzczMmM1/LmpwZw" },
        new Character { Id = 35, Name = "Kenjaku", Gender = Gender.Masculino, Affiliations = new List<string>{"Grupo do Kenjaku"}, Species = Species.Humano, Classification = Classification.UsuárioDeMaldição, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2017, PhotoUrl = "https://imgs.search.brave.com/sc9hSzE6_2v_C1MAJnOneMREMZi89FArHU5H3E-AuGg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Z2Vla2xhbmRvLmNv/bS5ici93cC1jb250/ZW50L3VwbG9hZHMv/MjAyNS8wMS9pbWFn/ZS0xMC0xMDI0eDU3/Ni5wbmc" },
        new Character { Id = 36, Name = "Uraume", Gender = Gender.Outro, Affiliations = new List<string>{"Grupo do Kenjaku"}, Species = Species.Humano, Classification = Classification.UsuárioDeMaldição, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2020, PhotoUrl = "https://imgs.search.brave.com/Vog6m0_wdveEZhy43QMW0nDlFHib3cB-IPNNzX2rKxE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2MwLzVk/LzM5L2MwNWQzOTkx/OWRjNTA5MTA2NjIw/NGI2ODljYjdlMzY2/LmpwZw" },
        new Character { Id = 37, Name = "Toji Fushiguro", Gender = Gender.Masculino, Affiliations = new List<string>{"Clã Zen'in"}, Species = Species.Humano, Classification = Classification.Civil, CombatStyle = CombatStyle.ArmaAmaldiçoada, DebutYear = 2019, PhotoUrl = "https://imgs.search.brave.com/-axBToir9UXhRuHeFRw-xmFGaXqandk1jWgXRTnBoZg/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJzLmNvbS9p/bWFnZXMvaGQvdG9q/aS1mdXNoaWd1cm8t/bmlnaHR0aW1lLXN0/YW5jZS11NnlkdjBi/NTFjeGc0ZGE5Lmpw/Zw" },
        new Character { Id = 38, Name = "Naoya Zenin", Gender = Gender.Masculino, Affiliations = new List<string>{"Clã Zen'in"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2021, PhotoUrl = "https://imgs.search.brave.com/X7ilr_S8vo5m3mk018KbC166-8DO5OI3uIMTuNA5Lzk/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zMy5h/bWF6b25hd3MuY29t/L2NvbWljZ2Vla3Mv/Y2hhcmFjdGVycy9h/dmF0YXJzLzUwNDYz/LmpwZz90PTE2ODIz/MTk4MDg" },
        new Character { Id = 39, Name = "Naobito Zenin", Gender = Gender.Masculino, Affiliations = new List<string>{"Clã Zen'in"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2020, PhotoUrl = "https://imgs.search.brave.com/kSXn0zfMuWZmbxnhDLX41Jf1SsTyjnSYONVIr2AhOP8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/YW5pc2VhcmNoLmZy/L2ltYWdlcy9jaGFy/YWN0ZXIvY292ZXIv/OTcvOTc3NzJfNDAw/LndlYnA" },
        new Character { Id = 40, Name = "Junpei Yoshino", Gender = Gender.Masculino, Affiliations = new List<string>{"Nenhuma"}, Species = Species.Humano, Classification = Classification.UsuárioDeMaldição, CombatStyle = CombatStyle.Shikigami, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/jsegYcV_HnJr6J-eB-bgGr5I31yj7fN5pqEL7oJFlSs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90aGlj/Yy11d3UubXl3YWlm/dWxpc3QubW9lL3dh/aWZ1cy9qdW5wZWkt/eW9zaGluby82R1hP/cDNrbEhoTW9Uemlu/QktvUmJKRmx2QUlB/OXlJY2w2YWNleURB/LmpwZz9jbGFzcz10/aHVtYm5haWw" },
        new Character { Id = 41, Name = "Haruta Shigemo", Gender = Gender.Masculino, Affiliations = new List<string>{"Grupo do Kenjaku"}, Species = Species.Humano, Classification = Classification.UsuárioDeMaldição, CombatStyle = CombatStyle.ArmaAmaldiçoada, DebutYear = 2020, PhotoUrl = "https://imgs.search.brave.com/odD97vKPi31XoCbUkvxsLtQX43e5PhefFjrfAl5fEEI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzFiLzVj/LzYwLzFiNWM2MDg0/OGY5ZTliNmQwNjFm/ZTAzYTM1Y2NlNGMx/LmpwZw" },
        new Character { Id = 42, Name = "Hana Kurusu", Gender = Gender.Feminino, Affiliations = new List<string>{"Nenhuma"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2021, PhotoUrl = "https://imgs.search.brave.com/28-7yJtHxKJlrT0c9HgfqrvofTrj6EOYamw1aWVkQ-4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMud2lraWEubm9j/b29raWUubmV0L2p1/anV0c3Uta2Fpc2Vu/L2ltYWdlcy9kL2Rm/L0hhbmFfS3VydXN1/XyhWb2x1bWVfMjQp/LnBuZy9yZXZpc2lv/bi9sYXRlc3Qvc2Nh/bGUtdG8td2lkdGgt/ZG93bi8yNjg_Y2I9/MjAyMzA5MTkxMjI2/NDY" },
        new Character { Id = 43, Name = "Hiromi Higuruma", Gender = Gender.Masculino, Affiliations = new List<string>{"Nenhuma"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2021, PhotoUrl = "https://imgs.search.brave.com/AKNpPneAIcBmTQ7WAx0dSReWKAbMPuTPMYScFEgPsSE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pMS5z/bmRjZG4uY29tL2Fy/dHdvcmtzLUpuQnh3/NklHWEROajI4S1Yt/bmVQNXR3LXQxMDgw/eDEwODAuanBn" },
        new Character { Id = 44, Name = "Hajime Kashimo", Gender = Gender.Masculino, Affiliations = new List<string>{"Nenhuma"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2021, PhotoUrl = "https://imgs.search.brave.com/ko-KafmsfjoZp9GGQjm-nj9PcMV-sG6KQH5rPu4LJeQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMud2lraWEubm9j/b29raWUubmV0L2p1/anV0c3Uta2Fpc2Vu/L2ltYWdlcy84Lzgx/L0hhamltZV9LYXNo/aW1vXyhWb2x1bWVf/MjEpLnBuZy9yZXZp/c2lvbi9sYXRlc3Qv/c2NhbGUtdG8td2lk/dGgtZG93bi8yNjg_/Y2I9MjAyMjExMTAy/MDI0MDQ" },
        new Character { Id = 45, Name = "Yorozu", Gender = Gender.Feminino, Affiliations = new List<string>{"Nenhuma"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2022, PhotoUrl = "https://imgs.search.brave.com/brJBOW8kupeJBoce72IrYfMA_U34_8J5TpWX2zCyQ3s/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jcml0/aWNhbGhpdHMuY29t/LmJyL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDIzLzEyL2U0YTJl/ZDE0MDUyZTA4ZDQ3/ZTlmZTJlYmRhNDMz/Mjg3LmpwZw" },
        new Character { Id = 46, Name = "Fumihiko Takaba", Gender = Gender.Masculino, Affiliations = new List<string>{"Nenhuma"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2021, PhotoUrl = "https://imgs.search.brave.com/GYgAAJDKCSNYPF9_gv5uvPGS_wLC92ts3jGnO2X0tBw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWNnLnNwb3J0c2tl/ZWRhLmNvbS9lZGl0/b3IvMjAyNC8xMi80/ZWQ1Zi0xNzMzMDgy/ODE4MDEzMC0xOTIw/LmpwZw" },
        new Character { Id = 47, Name = "Rika Orimoto", Gender = Gender.Feminino, Affiliations = new List<string>{"Nenhuma"}, Species = Species.Maldição, Classification = Classification.MestreDeMaldição, CombatStyle = CombatStyle.CorpoACorpo, DebutYear = 2017, PhotoUrl = "https://imgs.search.brave.com/6jCYa8PwUPa0hC4e75gcSmKwjGKocb74z7TjkDIjC7Y/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzliLzQ1/L2I1LzliNDViNTI3/OTdjZjllNDY5NWVi/YzQ3ZTBmOGI0ZmI1/LmpwZw" },
        new Character { Id = 48, Name = "Takako Uro", Gender = Gender.Feminino, Affiliations = new List<string>{"Esquadrão de Assassinos"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2022, PhotoUrl = "https://imgs.search.brave.com/TtYI8DsTOeuv7e9Mg_5CbHQsBLk1fW4aXVGepyrF8Eo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzk5L2Y0/L2FjLzk5ZjRhY2Rl/MjNhYzg4ZTM3YjEy/NGY4MjM1YWUyZTY4/LmpwZw" },
        new Character { Id = 49, Name = "Ryu Ishigori", Gender = Gender.Masculino, Affiliations = new List<string>{"Nenhuma"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2022, PhotoUrl = "https://imgs.search.brave.com/Adhgx9JN4xUjPxPJv0geb20zKkLYcKmGH-NsGYVSN8k/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzL2I0Lzdi/L2JiL2I0N2JiYjRj/NjNjYWJiOGM0YzJh/NzQ1YTY5OWE1OWJh/LmpwZw" },
        new Character { Id = 50, Name = "Miguel", Gender = Gender.Masculino, Affiliations = new List<string>{"Grupo do Geto"}, Species = Species.Humano, Classification = Classification.UsuárioDeMaldição, CombatStyle = CombatStyle.CorpoACorpo, DebutYear = 2017, PhotoUrl = "https://imgs.search.brave.com/zLK_-qdEHV7N5bUD954DRdkLbuXoOxuh2-IZrOGLDrY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzI0LzU5/LzYyLzI0NTk2MmMx/ZDhmNzI5N2ViODVl/Njc2MzQ3OWU2NjUy/LmpwZw" },
        new Character { Id = 51, Name = "Yu Haibara", Gender = Gender.Masculino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.CorpoACorpo, DebutYear = 2018, PhotoUrl = "https://imgs.search.brave.com/6rptKnphhORn1e6PPvU5Zpwag3Mxy7FsECSLHE25Aec/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZGV4ZXJ0by5jb20v/Y2RuLWltYWdlL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDIzLzA4/LzA0L2p1anV0c3Ut/a2Fpc2VuLXl1LWhh/aWJhcmEuanBlZz93/aWR0aD0xMjAwJnF1/YWxpdHk9NjAmZm9y/bWF0PWF1dG8" },
        new Character { Id = 52, Name = "Mimiko Hasaba", Gender = Gender.Feminino, Affiliations = new List<string>{"Grupo do Geto"}, Species = Species.Humano, Classification = Classification.UsuárioDeMaldição, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2017, PhotoUrl = "https://imgs.search.brave.com/71_ji6reScirEfXWJOccBiByugwl1ex-XO3VoKMaNQw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzUwLzcw/LzY5LzUwNzA2OWE4/NWExY2Q1NTg2MmRh/Y2ZhMTFmYWUxMDlh/LmpwZw" },
        new Character { Id = 53, Name = "Nanako Hasaba", Gender = Gender.Feminino, Affiliations = new List<string>{"Grupo do Geto"}, Species = Species.Humano, Classification = Classification.UsuárioDeMaldição, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2017, PhotoUrl = "https://imgs.search.brave.com/W0lpUtZ93pX_2BjKtq_GFLKPDct8NptBmVcTz36tLm4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pLnBp/bmltZy5jb20vb3Jp/Z2luYWxzLzJmLzg1/LzRkLzJmODU0ZGQ4/YmU1YWExM2I3MmFk/MDgwOTU3ODE1YTQx/LmpwZw" },
        new Character { Id = 54, Name = "Tengen", Gender = Gender.Feminino, Affiliations = new List<string>{"Escola Jujutsu de Tóquio"}, Species = Species.Humano, Classification = Classification.Feiticeiro, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2019, PhotoUrl = "https://imgs.search.brave.com/WL8SJtpuYb2JTDeCdBbW3QDweTyeozu7SE2RgrTl1Hs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMtd2l4bXAtZWQz/MGE4NmI4YzRjYTg4/Nzc3MzU5NGMyLndp/eG1wLmNvbS9mLzg4/ODRkOTRjLWFkN2Et/NGNiZC1iODNiLTZi/MWY2MjZhYTJlYi9k/ZjF0c3plLTE1N2Rk/YWI2LTExYWItNGU2/My04YzJhLTlhZTMz/ZDY4YzE3NC5qcGc_/dG9rZW49ZXlKMGVY/QWlPaUpLVjFRaUxD/SmhiR2NpT2lKSVV6/STFOaUo5LmV5Snpk/V0lpT2lKMWNtNDZZ/WEJ3T2pkbE1HUXhP/RGc1T0RJeU5qUXpO/ek5oTldZd1pEUXhO/V1ZoTUdReU5tVXdJ/aXdpYVhOeklqb2lk/WEp1T21Gd2NEbzNa/VEJrTVRnNE9UZ3lN/alkwTXpjellUVm1N/R1EwTVRWbFlUQmtN/alpsTUNJc0ltOWlh/aUk2VzF0N0luQmhk/R2dpT2lKY0wyWmNM/emc0T0RSa09UUmpM/V0ZrTjJFdE5HTmla/QzFpT0ROaUxUWmlN/V1kyTWpaaFlUSmxZ/bHd2WkdZeGRITjZa/UzB4TlRka1pHRmlO/aTB4TVdGaUxUUmxO/ak10T0dNeVlTMDVZ/V1V6TTJRMk9HTXhO/elF1YW5CbkluMWRY/U3dpWVhWa0lqcGJJ/blZ5YmpwelpYSjJh/V05sT21acGJHVXVa/RzkzYm14dllXUWlY/WDAuTmc3RUdoTVB0/eno3TFNKYWIxU0Vz/UTVxbHRINlY3TkRB/WkQxRW1tS0FWNA" },
        new Character { Id = 55, Name = "Tsumiki Fushiguro", Gender = Gender.Feminino, Affiliations = new List<string>{"Nenhuma"}, Species = Species.Humano, Classification = Classification.Civil, CombatStyle = CombatStyle.TécnicaInata, DebutYear = 2019, PhotoUrl = "https://imgs.search.brave.com/1BvqRKocVdQxcf0uRaDpBrTlmNZkyA2Dv-IYVBKKBlU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90aGlj/Yy11d3UubXl3YWlm/dWxpc3QubW9lL3dh/aWZ1cy90c3VtaWtp/LWZ1c2hpZ3Vyby1z/b3JjZXJ5LWZpZ2h0/L2V2NmFJVlo5Zk5J/d2J3V1FUOGtTMDVx/V0hQTEdsU1dnajNU/ZTgwT0ouanBnP2Ns/YXNzPXRodW1ibmFp/bA" }
    };
}
    

    public Task<Character> GetCharacterOfTheDayAsync()
    {
        var dayIndex = DateTime.Now.DayOfYear % _allCharacters.Count;
        return Task.FromResult(_allCharacters[dayIndex]);
    }

    public Task<Character> FindCharacterByNameAsync(string name)
    {
        var character = _allCharacters.FirstOrDefault(c => c.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
        return Task.FromResult(character);
    }
    
    public Task<List<string>> GetAllCharacterNamesAsync()
    {
        var names = _allCharacters.Select(c => c.Name).OrderBy(name => name).ToList();
        return Task.FromResult(names);
    }


    public Task<Character> GetRandomCharacterAsync()
    {
        var random = new Random();
        var randomIndex = random.Next(0, _allCharacters.Count);
        var character = _allCharacters[randomIndex];
        return Task.FromResult(character);
    }

    public Task<Character> GetCharacterByIdAsync(int id)
    {
        var character = _allCharacters.FirstOrDefault(c => c.Id == id);
        return Task.FromResult(character);
    }
}